# Project: test
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = test01.o test02.o
LINKOBJ  = test01.o test02.o
LIBS     = -L"D:/develop/Dev-Cpp/MinGW64/lib" -L"D:/develop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/develop/Dev-Cpp/MinGW64/include" -I"D:/develop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/develop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/develop/Dev-Cpp/MinGW64/include" -I"D:/develop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/develop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/develop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = test.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

test01.o: test01.c
	$(CC) -c test01.c -o test01.o $(CFLAGS)

test02.o: test02.c
	$(CC) -c test02.c -o test02.o $(CFLAGS)
